#!/usr/bin/env ruby
require "fileutils"

target_dir = ARGV[0] ? File.expand_path(ARGV[0]) : Dir.pwd

unless Dir.exist?(target_dir)
  puts "Directory does not exist: #{target_dir}"
  exit 1
end

Dir.children(target_dir).each do |entry|
  source_dir = File.join(target_dir, entry)
  next unless File.directory?(source_dir)

  Dir.children(source_dir).each do |item|
    src  = File.join(source_dir, item)
    dest = File.join(target_dir, item)

    if File.exist?(dest)
      base = File.basename(item, ".*")
      ext  = File.extname(item)
      i = 1
      loop do
        new_name = "#{base}_#{i}#{ext}"
        dest = File.join(target_dir, new_name)
        break unless File.exist?(dest)
        i += 1
      end
    end

    FileUtils.mv(src, dest)
  end

  Dir.rmdir(source_dir) if Dir.empty?(source_dir)
end

