#!/usr/bin/env ruby

# This is a utility to convert virgin file names with space with chad file names with dashes.
# Can be used to replace underscores with dashes. Or any character with any character to be precise.

require 'optparse'
require 'pry-byebug'


real_mode = true
replace_char = " "
replace_with_char = "-"

hash_options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: space-to-dash [options]"
  opts.on('-d [ARG]', '--depth [ARG]', "Specify the depth") do |v|
    hash_options[:depth] = v
  end
  opts.on('-h', '--help', 'Display this help') do 
    puts opts
    exit
  end
end.parse!


max_depth = hash_options[:depth] || '1'
max_depth = max_depth.to_i

(1..max_depth).each do |depth|
  file_names_string = `find . -mindepth #{depth} -maxdepth #{depth}`
  file_names = file_names_string.split("\n")
  file_names.each do |file_name|
    new_file_name = file_name.gsub(replace_char, replace_with_char)
    next if new_file_name == file_name

    command = %{mv "#{file_name}" "#{new_file_name}"}
    if real_mode
      `#{command}`
    else
      puts(command)
    end
  end
end
